### PR TITLE
Modify the build/clean scripts to recursively search for Makefiles

### PR DESCRIPTION
**Pull request by aagallag**

### CODE REVIEW

**Comment by yne** [comment]
The same could be achieved using :
`for directory in */Makefile; do`

So, you can simply build all the sample using :
`for f in */Makefile; do make -C ${f%/*} all; done`

(replace the `all` target with `clean` to clean all sample)

**Comment by aagallag** [comment]
Thanks for the suggestion, however, I noticed an issue when testing it.

While the change did resolve the error message I was previously seeing, it doesn't actually compile the ./net/http/ project.

Build Script Output:
```
$ ./build.sh 
make: Entering directory '~/samples/hello_cpp_world'
mkdir -p out/./
arm-vita-eabi-g++ -c -std=c++11 -o out/main.o src/main.cpp
arm-vita-eabi-g++ -Wl,-q -o hello_cpp_world.elf out/main.o
arm-vita-eabi-strip -g hello_cpp_world.elf
vita-elf-create hello_cpp_world.elf hello_cpp_world.velf
vita-make-fself hello_cpp_world.velf eboot.bin
vita-mksfoex -s TITLE_ID="FFFF00001" "HelloWorld" param.sfo
vita-pack-vpk -s param.sfo -b eboot.bin \
	--add sce_sys/icon0.png=sce_sys/icon0.png \
	--add sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png \
	--add sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png \
	--add sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml \
hello_cpp_world.vpk
make: Leaving directory '~/samples/hello_cpp_world'
make: Entering directory '~/samples/hello_world'
mkdir -p out/./
arm-vita-eabi-g++ -c -o out/main.o src/main.c
arm-vita-eabi-g++ -Wl,-q -o hello_cpp_world.elf out/main.o
arm-vita-eabi-strip -g hello_cpp_world.elf
vita-elf-create hello_cpp_world.elf hello_cpp_world.velf
vita-make-fself hello_cpp_world.velf eboot.bin
vita-mksfoex -s TITLE_ID="FFFF00001" "HelloWorld" param.sfo
vita-pack-vpk -s param.sfo -b eboot.bin \
	--add sce_sys/icon0.png=sce_sys/icon0.png \
	--add sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png \
	--add sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png \
	--add sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml \
hello_cpp_world.vpk
make: Leaving directory '~/samples/hello_world'
```

See Commit: 5113258339eea1cbf45d1cb32bfd93408d31c9aa

I admit my implementation seems to be needlessly complex, so please let me know if you have another idea!

**Comment by yne** [comment]
I've fixed this issue by flattening samples directories.
So the `/net/http` sample is now `/net_http`. See : https://github.com/vitasdk/samples/pull/5/commits/3a4b716e281af6b30f0b551b963ea0bfa05ce7ec


But maybe we could name the folder just like the demonstrated SCE library.
Example: Sample that use sceHttp* function could be named `/http_basic` , `/http_cookie`, `/http_thread`...

Basically, when this repository will have dozens of samples (I hope it will),  I seriously doubt that people will build all of them. They will simply go the the sample they are interested in an build-install-run it.

**Comment by xyzz** [comment]
no need for that anymore

**Pull request closed without merging**
