### PR TITLE
Add printf attribut to psvDebugScreenPrintf

### PR DESCRIPTION
**Pull request by yne**
So we can now have format related warning

### CODE REVIEW

**Comment by CelesteBlue-dev** [comment]
So now if I type printf("%i"); I'll see a warning ?

**Comment by yne** [comment]
Yes, but also on type missmatch, see:

```
/main.c:30:25: warning: format '%i' expects argument of type 'int', but argument 2 has type 'double' [-Wformat=]
  psvDebugScreenPrintf("%i",.1);
                        ~^
                        %f
```

**Comment by CelesteBlue-dev** [comment]
This warning is very annoying because it happens even when type is good...
So currently there is no warning at all ?

**Comment by yne** [comment]
>This warning is very annoying because it happens even when type is good...

Pretty sure it does not...

>So currently there is no warning at all ?

No there is not format check at this moment (which is dangerous because you could swap a `%s` with a `%i` which lead to a segfault), hence this PR.

**Pull request merged**
