### PR TITLE
Fix hello_cpp_world sample

### PR DESCRIPTION
**Pull request by beelzebielsk**
Initially, the C++ hello world program quit immediately, and also didn't actually print anything. I copied the structure from the hello world C program, and a little from the json sample. Let me know if there's a better way to do this for C++, I'll change it.

### CODE REVIEW

**Comment by isage** [comment]
It prints to stdout (tty), you need a plugin (princesslog or psmlogusb) to see tty output.

**Comment by beelzebielsk** [comment]
Ok, noted. What does that mean for this pull request, though? What should be changed? Should I change some documentation somewhere to note these plugin(s) as a prerequisite for hello_cpp_world? I prefer this way though, since it doesn't require a plugin, and every other C++ sample does things this way.

**Comment by beelzebielsk** [comment]
Also, when you say tty, do you mean a terminal on a computer? Or are you saying the black screen in the app is a tty?

**Comment by Princess-of-Sleeping** [comment]
I have crashed this code with latest commiit.

**Pull request merged**
